### ISSUE TITLE
Поправить таблицу в записях

### ISSUE THREAD

**Issue by orby-tech** [roll-over/landing#34]
1) Убрать паддинги между строками
2) Скруглить подсветку сломанных полей
3) 

![Image](https://github.com/roll-over/landing/assets/59844758/fdb02022-544e-4d0d-af88-3e553c8ef0e0)

**Comment by yuraautsayder** [comment]
Фиксирую визуал страницы до начала работ т.к. после постановки таски верстка изменилась  

![Image](https://github.com/roll-over/landing/assets/54168866/d103bbe9-2287-4639-9c0e-f185c603343c)

**Comment by yuraautsayder** [comment]
@orby-tech я бы хотел предложить такой вариант, либо от него как-то отталкиваться, в действующем варианте кнопка выходит за рамки и выбивается по цвету из общей массы


![Image](https://github.com/roll-over/landing/assets/54168866/e5a84504-6bfb-41c0-b8ce-8bbd34fb36ee)

**Comment by yuraautsayder** [comment]
> По поводу кнопки, есть компонент EditButton и мне кажется стоит с ним работать (Возможно его не было когда версталась эта страница)

Не совсем верно задал вопрос, поясняю:  да, это компонент и мы работаем с ним, но, я еще не особо знаю црмку, предположил, что он еще где-то используется и имеет-ли смысл менять ему цвет для всех мест его применения или стоит создать новую кнопку с этим цветом и использовтаь её тут?

**Comment by orby-tech** [comment]
> > По поводу кнопки, есть компонент EditButton и мне кажется стоит с ним работать (Возможно его не было когда версталась эта страница)
> 
> Не совсем верно задал вопрос, поясняю: да, это компонент и мы работаем с ним, но, я еще не особо знаю црмку, предположил, что он еще где-то используется и имеет-ли смысл менять ему цвет для всех мест его применения или стоит создать новую кнопку с этим цветом и использовтаь её тут?

Стоит менять саму кнопку, пока не хочу раздувать колличество элементов

Главное проверить, что все работает корректно и на 5175 порту
